import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
import markdown2
import config

logger = logging.getLogger("EdgeAIScout")

class Mailer:
    def __init__(self):
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.user = config.SMTP_USER
        self.password = config.SMTP_PASS
        self.receiver = config.RECEIVER_MAIL

    def convert_markdown_to_html(self, markdown_content):
        """
        Converts Markdown to HTML with Outlook-friendly styling.
        """
        # Convert MD to basic HTML
        html_body = markdown2.markdown(markdown_content)

        # HTML Template with CSS
        # Outlook styling: Arial font, table styling, clean layout.
        # Added ul/li styling for nested lists from Delta analysis
        html_content = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    font-size: 14px;
                    line-height: 1.6;
                    color: #333333;
                    background-color: #f9f9f9;
                    margin: 0;
                    padding: 20px;
                }}
                .container {{
                    max_width: 800px;
                    margin: 0 auto;
                    background-color: #ffffff;
                    padding: 30px;
                    border: 1px solid #dddddd;
                    border-radius: 5px;
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 2px solid #3498db;
                    padding-bottom: 10px;
                    font-size: 24px;
                }}
                h2 {{
                    color: #e67e22;
                    margin-top: 30px;
                    font-size: 20px;
                    border-bottom: 1px solid #eeeeee;
                    padding-bottom: 5px;
                }}
                h3 {{
                    color: #2980b9;
                    font-size: 18px;
                    margin-top: 25px;
                    margin-bottom: 5px;
                }}
                a {{
                    color: #3498db;
                    text-decoration: none;
                }}
                a:hover {{
                    text-decoration: underline;
                }}
                ul {{
                    padding-left: 20px;
                    margin-top: 5px;
                    margin-bottom: 10px;
                }}
                li {{
                    margin-bottom: 5px;
                }}
                strong {{
                    color: #555555;
                }}
                hr {{
                    border: 0;
                    height: 1px;
                    background: #eeeeee;
                    margin: 20px 0;
                }}
                .footer {{
                    margin-top: 40px;
                    font-size: 12px;
                    color: #999999;
                    text-align: center;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                {html_body}
                <div class="footer">
                    <p>Generated by Edge AI Scout</p>
                </div>
            </div>
        </body>
        </html>
        """
        return html_content

    def send_report(self, markdown_content, date_str):
        """
        Sends the daily report via email.
        """
        if not self.user or not self.password or not self.receiver:
            logger.warning("Email configuration missing (SMTP_USER, SMTP_PASS, RECEIVER_MAIL). Skipping email dispatch.")
            return

        try:
            logger.info("Preparing email report...")
            html_content = self.convert_markdown_to_html(markdown_content)

            message = MIMEMultipart("alternative")
            message["Subject"] = f"Edge AI Scout Report - {date_str}"
            message["From"] = self.user
            message["To"] = self.receiver

            # Attach parts (Plain text version could be added, but focusing on HTML)
            # part1 = MIMEText(markdown_content, "plain")
            part2 = MIMEText(html_content, "html")

            # message.attach(part1)
            message.attach(part2)

            # Send
            logger.info("Connecting to SMTP server...")
            context = ssl.create_default_context()
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.user, self.password)
                server.sendmail(self.user, self.receiver, message.as_string())

            logger.info(f"Email sent successfully to {self.receiver}")

        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP Authentication failed. Check username and password.")
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
