import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Optional
import logging
import markdown2
import config

logger = logging.getLogger("EdgeAIScout")

# Localized email subject
EMAIL_SUBJECTS = {
    "de": "Edge AI Scout Report - {date}",
    "en": "Edge AI Scout Report - {date}",
}


class Mailer:
    def __init__(self):
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.user = config.SMTP_USER
        self.password = config.SMTP_PASS
        self.receiver = config.RECEIVER_MAIL

    def convert_markdown_to_html(self, markdown_content):
        """
        Converts Markdown to HTML with Outlook-friendly styling.
        """
        html_body = markdown2.markdown(markdown_content)

        html_content = f"""
        <html>
        <head>
            <style>
                /* Reset & Base */
                body {{
                    font-family: 'Segoe UI', Arial, sans-serif;
                    font-size: 14px;
                    line-height: 1.5;
                    color: #333333;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 20px;
                }}
                .container {{
                    max-width: 700px;
                    margin: 0 auto;
                    background-color: #ffffff;
                    padding: 40px;
                    border: 1px solid #e0e0e0;
                    border-radius: 8px;
                    box-shadow: 0 2px 5px rgba(0,0,0,0.05);
                }}

                /* Headings */
                h1 {{
                    color: #1a202c;
                    border-bottom: 3px solid #3182ce;
                    padding-bottom: 15px;
                    font-size: 26px;
                    margin-bottom: 25px;
                }}
                h2 {{
                    color: #2d3748;
                    margin-top: 40px;
                    margin-bottom: 15px;
                    font-size: 20px;
                    background-color: #f7fafc;
                    padding: 10px;
                    border-left: 4px solid #3182ce;
                    border-radius: 4px;
                }}
                h3 {{
                    color: #4a5568;
                    font-size: 16px;
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                    margin-top: 25px;
                    margin-bottom: 10px;
                    border-bottom: 1px solid #edf2f7;
                    padding-bottom: 5px;
                }}

                /* Typography */
                p {{ margin-bottom: 15px; }}
                strong {{ color: #2d3748; font-weight: 600; }}
                em {{ color: #718096; font-size: 13px; }}
                blockquote {{
                    border-left: 3px solid #cbd5e0;
                    margin: 0 0 20px 0;
                    padding: 10px 15px;
                    background-color: #f8fafc;
                    color: #4a5568;
                    font-style: italic;
                }}
                a {{ color: #3182ce; text-decoration: none; font-weight: 500; }}
                a:hover {{ text-decoration: underline; }}

                /* Lists (Outlook Fixes) */
                ul {{
                    padding-left: 20px;
                    margin-top: 5px;
                    margin-bottom: 15px;
                }}
                li {{
                    margin-bottom: 6px;
                    padding-left: 5px;
                }}

                /* Divider */
                hr {{
                    border: 0;
                    height: 1px;
                    background: #e2e8f0;
                    margin: 40px 0;
                }}

                /* Footer */
                .footer {{
                    margin-top: 50px;
                    font-size: 12px;
                    color: #a0aec0;
                    text-align: center;
                    border-top: 1px solid #edf2f7;
                    padding-top: 20px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                {html_body}
                <div class="footer">
                    <p>Generated by Edge AI Scout • {datetime.now().year}</p>
                </div>
            </div>
        </body>
        </html>
        """
        return html_content

    def send_report(
        self,
        markdown_content: str,
        date_str: str,
        recipients: Optional[List[str]] = None,
        language: str = "de",
    ) -> None:
        """
        Send report to one or more recipients.
        
        Each recipient receives an individual email to avoid exposing addresses.
        
        Args:
            markdown_content: Markdown content of the report
            date_str: Date string for the report
            recipients: List of email addresses. If None, uses legacy self.receiver
            language: Language code for localized subject (default: "de")
        """
        # Determine recipients
        if recipients:
            to_list = recipients
        elif self.receiver:
            to_list = [self.receiver]
        else:
            to_list = []
        
        if not self.user or not self.password or not to_list:
            logger.warning("Email configuration missing or no recipients. Skipping email dispatch.")
            return

        try:
            logger.info(f"Preparing email report for {len(to_list)} recipient(s)...")
            html_content = self.convert_markdown_to_html(markdown_content)

            # Get localized subject
            subject_template = EMAIL_SUBJECTS.get(language, EMAIL_SUBJECTS["en"])
            subject = subject_template.format(date=date_str)

            logger.info("Connecting to SMTP server...")
            context = ssl.create_default_context()
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.user, self.password)
                
                # Send individual emails to each recipient to avoid leaking addresses
                for recipient in to_list:
                    message = MIMEMultipart("alternative")
                    message["Subject"] = subject
                    message["From"] = self.user
                    message["To"] = recipient
                    message.attach(MIMEText(html_content, "html"))
                    
                    server.sendmail(self.user, [recipient], message.as_string())

            logger.info(f"Email sent successfully to {len(to_list)} recipient(s)")

        except Exception as e:
            logger.error(f"Failed to send email: {e}")
